#!/usr/bin/env python
import csv
import sys

with open(sys.argv[1], 'r') as csvfile:
    reader = csv.reader(csvfile, quotechar='"')
    firstline = True
    for row in reader:
        if firstline:    #skip first line
            firstline = False
            continue
        print(row[-1]) # row[-1] gives the last column