#!/bin/bash
# minimal script for testing stuff
thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
thisAuth=$(python $thisDir/get.auth.py)
#
# Stuff goes here.

partMtg=$1
tmp=~/tmp/zoom
curl -s --location --request GET \
     'https://api.zoom.us/v2/metrics/meetings/91805352246/participants/qos?page_size=1&type=past' \
     --header 'Authorization: Bearer '"$thisAuth" \
     --header 'Cookie: _zm_lang=en-US; cred=DF1D1094C925352ECFFAE5C05E468CA4' -o "$tmp"/"$partMtg".qos.json
