#!/bin/bash
#
tmp=~/tmp/wa
tsvFile=$tmp/stats.tsv
#csvFile=$tmp/stats.csv
statsFile=~/$(date +"%Y-%m-%d-%H-%M").xlsx
#
:>"$csvFile"
:>"$tsvFile"

#get.events.sh -vru
while IFS='' read -r thisCourse ; do
    jq -r '.[]|[.RegistrationDate,.Event.Name] | @tsv' $tmp/$thisCourse.registrations.json >> $tsvFile
done < $tmp/events.list

