#!/bin/bash
# This script fetches the WISE Events Calendar in .ics format
#
# Store calendar url in ~/.WISEcal
# Get URL from WISE Events Calendar settings, .ics output
thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
URL=$(cat ~/.WISECal)
curl -s $URL -o basic.ics
#
now=$(date +%s)
perl $thisDir/ics_line_unfolder.pl basic.ics | sed -f ~/WISE-Tools/cal.sed > unfolded.ics 
ical2json unfolded.ics
#

jq --raw-output '.[][] |.VEVENT[] | select(.DTSTART != null) |    [( .DTSTART|.[:4]+"-" +.[4:6]+"-" +.[6:8] +.[8:9]+.[9:11] +":" +.[11:13] +":" + .[13:15] + .[15:16] | fromdate ),     .SUMMARY, .DESCRIPTION] | @tsv' unfolded.json > basic.tsv
sort -o basic.tsv basic.tsv
gawk -F"\t" -v NOW=$now -f $thisDir/awk/cal.awk basic.tsv > save.the.date.html

