#!/bin/bash
# This script uses curl to push files to our server. 
# login information is in .netrc
#
# If it fails silently, make sure that .netrc has the proper machine name, the same as is used in the curl command.
#
# $myWA is the root directory, value stored in .bashrc or .zshrc
# https://[mydomain]
#
checkVar ()
{
     y=\$"$1"   # Name of variable (not value!).
     msg  $y    # $Junk
     x=`eval "expr \"$y\" "`
     msg $x
     if [ -z $x ];
     then
	 die "Missing variable $y"
     else
	 msg  "Done"
     fi
#     eval "$1=\"Some Different Text \""  # Assign new value.
}

msg()
{
    {
    if [  "$verbose" = true ];
    then
	msgString=$*
	printf "%s\n" "%% $msgString"
    fi
    }
}
die()
{
    msgString=$1
    printf "%s\n" "%% $msgString %%"
    exit
}
doit()
{
    curl $curlVerbose --anyauth --netrc-file ~/.netrc  ''"$myWA/resources/$thisDir/"'' -T $thisFile
}
getHelp()
{
    echo "-b  Blog and Bulletin indexes go to Documents/reference/"
    echo "-l  Files containing Zoom links go to Links" 
    echo "-w  Others go to Documents/website"
    echo "-c  Put files in Documents/class.assistants"
    echo "-t  tmp directory for files" 
}
while getopts "b:l:t:w:c:hsv" opt; do
    case ${opt} in
	b) # Blogs
	    thisFile=$OPTARG
	    thisDir="Documents/reference"
	    ;;
	c) # Class Assistants
	    thisFile=$OPTARG
	    thisDir="Documents/class.assistants"
	    ;;
	l) # Links
	    thisFile=$OPTARG
	    thisDir="Links"
	    msg "Putting $thisFile in $thisDir"
	    ;;
	t) # tools directory
	    thisFile=$OPTARG
	    thisDir="tools"
	    ;;
	w) # Other stuff
	    thisFile=$OPTARG
	    thisDir="Documents/website"
	    ;;
	h) # Print help and exit
	    getHelp
	    ;;
	s) # Silent mode
	    curlVerbose="-s"
	    ;;
	v)
	    # verbose mode
	    curlVerbose="--verbose"
	    ;;
	?)
	getHelp
	;;

    esac
    done

checkVar myWA
#checkVar moo

doit
