#!/bin/bash
# This script uses curl to push files to our server. 
# login information is in .netrc
# If it fails silently, make sure that .netrc has the proper machine name, the same as is used in the curl command.
#
# $myWA is the root directory, value stored in .bashrc
# https://[mydomain]

doit()
{
    curl -s --anyauth --netrc-file ~/.netrc  ''"$myWA/resources/$thisDir/"'' -T $thisFile
}
getHelp()
{
    echo "-b  Blog and Bulletin indexes go to Documents/reference/"
    echo "-l  Files containing Zoom links go to Links" 
    echo "-w  Others go to Documents/website"
    echo "-c  Put files in Documents/class.assistants"
    echo "-t  tmp directory for files" 
}
while getopts "b:l:t:w:c:h" opt; do
    case ${opt} in
	b) # Blogs
	    thisFile=$OPTARG
	    thisDir="Documents/reference"
	    ;;
	c) # Class Assistants
	    thisFile=$OPTARG
	    thisDir="Documents/class.assistants"
	    ;;
	l) # Links
	    thisFile=$OPTARG
	    thisDir="Links"
	    echo "Putting $thisFile in $thisDir"
	    ;;
	t) # tools directory
	    thisFile=$OPTARG
	    thisDir="tools"
	    ;;
	w) # Other stuff
	    thisFile=$OPTARG
	    thisDir="Documents/website"
	    ;;
	h) # Print help and exit
	    getHelp
	    ;;
	?)
	getHelp
	;;

    esac
    done

#createPutFile
doit
