#!/bin/bash
# This script uses curl to push files to our server. 
# login information is in .netrc
#
# If it fails silently, make sure that .netrc has the proper machine name, the same as is used in the curl command.
#
# $myWA is the root directory, value stored in .bashrc or .zshrc
# https://[mydomain]
#
### TODO
### If remote directory doesn't exist, create it. Will need to use sftp
### 1. Add command option to check/create remote dir -D <dir-name>
### 2. Change options to specify directory? -d <dir-name>. Default is top-level /resources
### 
curlVerbose="--silent "
#
checkVar ()
{
     y=\$"$1"   # Name of variable (not value!).
     msg  $y    # $Junk
     x=`eval "expr \"$y\" "`
     msg $x
     if [ -z $x ];
     then
	 die "Missing variable $y"
     else
	 msg  "Done"
     fi
}

msg()
{
    {
    if [  "$verbose" = true ];
    then
	msgString=$*
	printf "%s\n" "%% $msgString"
    fi
    }
}
die()
{
    msgString=$1
    printf "%s\n" "%% $msgString %%"
    exit
}
doit()
{
    curl $curlVerbose --anyauth --netrc-file ~/.netrc  ''"$myWA/resources/$thisDir/"'' -T $thisFile
}
help()
{
    thisScript=$(which "$0")
    sed -rn 's/^\s*### ?//;T;p' "$thisScript"
    exit
}

while getopts "b:l:t:w:c:hsv" opt; do
    case ${opt} in
	b) # Blogs
	    thisFile=$OPTARG
	    thisDir="Documents/reference"
	    ;;
	c) # Class Assistants
	    thisFile=$OPTARG
	    thisDir="Documents/class.assistants"
	    ;;
	l) # Links
	    thisFile=$OPTARG
	    thisDir="Links"
	    msg "Putting $thisFile in $thisDir"
	    ;;
	t) # tools directory
	    thisFile=$OPTARG
	    thisDir="tools"
	    ;;
	w) # Other stuff
	    thisFile=$OPTARG
	    thisDir="Documents/website"
	    ;;
	h) # Print help and exit
	    help
	    ;;
	s )
	    # silent mode
	    curlVerbose="--silent "
	    ;;
	v)
	    # verbose mode
	    curlVerbose="--verbose "
	    ;;
	?)
	help
	;;

    esac
    done

checkVar myWA
doit
