#!/bin/bash
# This script fetches the WISE Events Calendar in .ics format
#
# Store calendar url in ~/.WISEcal
# Get URL from WISE Events Calendar settings, .ics output
#
mungDate()
{
    this=$1
    # We chop up the .ics date into something that the date command can use
    echo "${this:0:4}-${this:3:2}-${this:5:2} ${this:3:2}:${this:3:2}"
}
URL="https://calendar.google.com/calendar/ical/7lplqb8n1ntd7curtffi3u2edk%40group.calendar.google.com/public/basic.ics"
curl $URL 
#
today=$(date +"%Y%m%dT%H%M%SZ")
ical2json basic.ics
jq -r '.VCALENDAR[].VEVENT[] | select(.DTSTART != null) |[ .DTSTART, .SUMMARY,.DESCRIPTION] | @tsv' basic.json > basic.tsv
sort -o basic.tsv basic.tsv
gawk -F"\t" -v now=$today -f ~/WISE-Tools/awk/cal.awk  basic.tsv
#> events.html
#gawk -F"\t" -v now=$today '{if( $1 > now) printf "%s\n", $2 }' basic.tsv
