#!/bin/bash
# This script fetches the WISE Events Calendar in .ics format
#
# Store calendar url in ~/.WISEcal
# Get URL from WISE Events Calendar settings, .ics output
URL=$(cat ~/.WISEcal)
wget $URL 
#
# mung it with node.js
