#!/bin/bash
# TODO Parse options to the `zoom` command
## TIL
## 1/12/21
## When we get this error, it means this
## "The Token's Signature resulted invalid when verified using the Algorithm: HmacSHA256"
## There's a problem with the Zoom Secret in .bashrc
##
trap "rm -vf this.* hosts.json cadaver.put " EXIT
set -e
start_time="$(date -u +%s)"
simple=false
download=false
help()
{
    thisScript=$(which "$0")
    sed -rn 's/^\s*### ?//;T;p' "$thisScript"
    exit
}
msg()
{
    if [  "$verbose" = true ];
    then
	msgString=$*
	echo "%% $msgString"
    fi
}
die()
{
    if [ "$Verbose" = true ];
    then
	msgString=$*
	echo "%% $msgString"
    fi
}
setup()
{
    rptType=$1
    thisAuth=$(python3 $thisDir/get.auth.py)
    justLinks=$tmp/just.links.tsv
    msg "Initializing $justLinks"
    :>"$justLinks"
    sortedLinks=$tmp/sorted.links.tsv
    msg "Doing setup for \$rptType $rptType "
    HTMLFile=$tmp/$rptFile
    msg "Initializing $HTMLFile"
    :>"$HTMLFile"
    if [[ $simple = "false" ]]; then
	echo "<link href="https://sf.wildapricot.org/BuiltTheme/tinted_tiles_partly_cloudy.v3.0/current/3a1388a7/styles/combined.css" rel="stylesheet" type="text/css">" > $HTMLFile
	echo "<style>body {margin-left: 30px;}</style>" >> $HTMLFile
	echo "<img src='/resources/Pictures/WISE-Logos/WISE-Logo-Full-Name.png'/>" >> $HTMLFile
	echo "<p>Return to the  <a href="https://assumptionwise.org">WISE Home page</a>" >> $HTMLFile
	echo "<h2>$rptTitle</h2>" >> "$HTMLFile"
	thisDate=$(date  +"%B %d, %Y %-I:%M %p")
	if [ -n "$thisNote" ]; then
	    msg "Got a note"
	    echo "<b>*** $thisNote ***</b>" >> $HTMLFile
	fi
    echo "<p>Updated: $thisDate" >> "$HTMLFile"
    fi
}
init()
{
    tmp=~/tmp/$start_time
    if [[ "$init" = false ]] ; then
	msg "Skipping initialization" 
	return
    fi
    msg "Doing initialization"
    mkdir -p "$tmp"
    touch "$tmp"/tmp.tmp
    rm -r "${tmp:?}"/*
    
}
getHosts()
{
    hostList=$tmp/hosts.list
    :>$hostList
    msg "Getting hosts"
    curl -s --location --request GET 'https://api.zoom.us/v2/users?status=active&page_size=30' \
	 --header 'Authorization: Bearer '"$thisAuth" -o hosts.json
	jq -r '.users[] | select(.type == 2)  | .id' hosts.json > $hostList
    msg "Got hosts"
}
getMeetings()
{
    if [[ "$init" = false ]] ; then
	msg "Skipping update of meeting"
	return
    fi
    if [[ "$getAll" = true ]]; then
	retrieveType="scheduled"
    else
	retrieveType="upcoming"	
    fi
	getHosts # returns $hostList
	while IFS='' read -r thisHost ; do
	    msg "Working on meetings for $thisHost"
	    curl -s --location --request GET \
		 'https://api.zoom.us/v2/users/'"$thisHost"'/meetings?page_size=300&type='$retrieveType \
		 --header 'Authorization: Bearer '"$thisAuth" -o "$tmp"/"$thisHost".info.json 
	done < $hostList
    jq --slurp ' .[] | .meetings[].id' "$tmp"/*info.json  > "$tmp"/all.meetings.list
    sort --unique > "$tmp"/meetings.list < "$tmp"/all.meetings.list
}
meetingBasics()
{
    msg "Working on \$trackingField $trackingField"
    msg "Initializing $cmd.list"
    rptTypeList=$tmp/this.list
    :>"$rptTypeList"
    getMeetings
    if [[ "$getAll" = true ]]; then
	showAll="?show_previous_occurrences=true"
    fi
    while IFS='' read -r thisMtg ; do
	if [[ "$init" = false ]] ; then
	    msg "Skipping update of $rptType details"
	else
	    curl -s --location --request GET \
		 'https://api.zoom.us/v2/meetings/'"$thisMtg"$showAll\
		 --header 'Authorization: Bearer '"$thisAuth"\
		 -o "$tmp"/"$thisMtg".details.json 
	fi
	gotItem=$(jq --arg TYPE "$trackingField" -f "$thisDir"/get.zoom.type.jq "$tmp"/"$thisMtg".details.json)
	gotTopic=$(jq  --arg TYPE "$trackingField" -f "$thisDir"/get.zoom.topic.jq  "$tmp"/"$thisMtg".details.json)
	if [[ $gotTopic = "" ]] ; then
	    if [[ $keepDetail = true ]]; then
		# Leaving next line for debugging purposes
    		mv "$tmp"/"$thisMtg".details.json  "$tmp"/"$thisMtg".nope.json
	    else
		rm "$tmp"/"$thisMtg".details.json
	    fi
	else
	    echo "$gotItem" >> "$rptTypeList" 
	fi
    done < "$tmp"/meetings.list
    gThisList=$rptTypeList
}

doCourses()
{
    properName=$1
    msg "Geting dates for $properName"
    meetingBasics Course

    for file in "$tmp"/*.details.json;
    do
	thisTopic=$(jq '.topic' "$file")
	if [[ $simple = "true" ]]; then
	    jqFile="$thisDir"/make.simple.course.links.jq
	    theseTimes=""
	else
	    jqFile="$thisDir"/make.course.links.jq
	    theseTimes=$(jq -r '.occurrences[] | if .status == "deleted" then  empty else .start_time  end' "$file" | xargs -I DATE date -d "DATE" +"%B %d %-I:%M %p" | xargs -I TIME printf "\t%s" TIME)
	fi
	thisLink=$(jq -r -f "$jqFile" "$file")
	echo "$thisLink	$theseTimes" >> "$justLinks"
    done
    msg "Initializing $sortedLinks"
    :>"$sortedLinks"
    if [[ $simple = "true" ]]; then
	printf "Course\tLink\tHost and CA\tPhone\tMeeting Id\tPasscode\tAlternate Hosts\n" > "$sortedLinks"
	sort --version-sort "$justLinks" >> "$sortedLinks"
	msg "Sorted links are in $sortedLinks"
    else
	sort --version-sort "$justLinks" >> "$sortedLinks"
	gawk -F '\t' -f "$awkFile" "$sortedLinks" >> "$HTMLFile"

	# Make sure we handle entities properly, editing in place
	recode utf8..ascii  "$HTMLFile"
	msg "Output file is $HTMLFile"
	push.to.wa.sh -l $HTMLFile

    fi
}
doMtg()
{

    meetingBasics $tracingField
    
    if compgen -G "$tmp"/*.details.json;
    then
	for file in "$tmp"/*.details.json;
	do
	    thisTopic=$(jq '.topic' "$file")
	    msg "Deep Work on $thisTopic"
	    thisURL=$(jq '.registration_url' $file)
	    if [  $thisURL = "null" ]; then
		thisURL=$(jq -r '.join_url' $file)
	    fi
	    echo $thisURL 
	    thisLink=$(jq -r --arg URL $thisURL -f "$thisDir"/make.registration.links.jq "$file")
	    theseTimes=$(jq -r -f "$thisDir"/get.times.jq "$file")
	    echo "$thisLink	$theseTimes" >> "$justLinks"
	done
	sort -t$'\t' -k8 $tmp/just.links.tsv > "$sortedLinks"
	gawk -F '\t' -f $awkFile "$sortedLinks" >> "$HTMLFile"
	sed -i "s/  / /g" $HTMLFile
	sed -ibak 's/\xE2\x80\x99/\&rsquo;/g' $HTMLFile
	else
	echo "<p>No "$trackingField"s scheduled." >> $HTMLFile
    fi
    msg "HTML Link file is $HTMLFile"
    push.to.wa.sh -l $HTMLFile
}
dblEncode()
{
    echo $1
    that=$(urlencode $1)
    echo $that
    other=$(urlencode $that)
    echo $other
}
doRecordings()
{
    recDir=/archives/Recordings
    msg "Geting recordings for $trackingField"
    since=$(date +%Y-%m-%d -d "30 days ago")
#    since="2021-02-01"

    curl -s --request GET \
	 --url 'https://api.zoom.us/v2/metrics/meetings?include_fields=tracking_fields&page_size=150&from='$since'&type=past' \
	 --header 'authorization: Bearer '"$thisAuth" > this.json
    jq --raw-output --arg TF "$trackingField" '.meetings[] | select (.tracking_fields != null) |. |select(.tracking_fields[].value == $TF) | [.start_time,.uuid, .topic ]| @tsv' this.json > this.tsv
     while IFS='	' read -r thisTime thisUUID thisTopic ; do
	 i=$((i+1))
	 dblEncode $thisUUID
	 curl -s --request GET \
	      --header 'authorization: Bearer '"$thisAuth" \
	       --url 'https://api.zoom.us/v2/meetings/'"$other"'/recordings' > $tmp/$i.json
	 code=$(jq '.code' $tmp/$i.json)
	 if [[ $code == "null" ]]; then 
	     jq -r ' select(. != .code) | [ (.recording_files[] | select( any(. == "MP4" ) ) | (.recording_start | fromdate), .play_url, .download_url),.topic] | @tsv' $tmp/$i.json > $tmp/$i.tsv
	     dlFile=$(awk -F'\t' '{print $3}' $tmp/$i.tsv)
	     # Build file name from Course ID and date of recording
	     if [[ $trackingField = "Course" ]];
		then 
		    recFile=$(gawk -F'\t' 'match($4,/([A-D,S][0-9]*)/,a) {printf "%s-", a[1]}; {print strftime("%Y-%m-%d-%H-%M", $1)".mp4"}' $tmp/$i.tsv)
	     else
		 recFile=$(gawk -F'\t' 'match($4,/(\w*)/,a) {printf "%s-", a[1]}; {print strftime("%Y-%m-%d-%H-%M", $1)".mp4"}' $tmp/$i.tsv)
		 
		 echo $recFile
	     fi
	     cat $tmp/$i.tsv >> $justLinks

	     getParticipants $thisUUID "$recFile"
	     rptParticipants "$recFile"
	     # Doing downloads. 

	     if [ -e "$recDir/$recFile" ]; then
		 msg "No need to download $recDir/$recFile"
	     else
		 msg "Downloading $recDir/$recFile here."
		 wget -q $dlFile -O $recDir/$recFile
	     fi
	 fi
     done < this.tsv
     echo "what size is $justLinks"
	if [ -s $justLinks ]; then 
	    sort -r "$justLinks" > "$sortedLinks"
	    gawk -F '\t' -f "$awkDir"/zoom.recordings.awk "$sortedLinks" >> "$HTMLFile"
	   else
	       echo "<p>No recordings for $trackingField at this time" >> $HTMLFile
	fi
	    msg "Output file is $HTMLFile"
	    sed -ibak 's/\xE2\x80\x99/\&rsquo;/g' $HTMLFile
	    push.to.wa.sh -t "$tmp" -l $HTMLFile
}
getParticipants()
{
    partFile=$other.participants
    partMtg="$1"
    local thisFile="$2"
    msg "Getting participants for $partMtg"
    curl -s --location --request GET \
	 'https://api.zoom.us/v2/metrics/meetings/'"$partMtg"'/participants?type=past' \
	 --header 'Authorization: Bearer '"$thisAuth" \
	 --header 'Cookie: _zm_lang=en-US; cred=DF1D1094C925352ECFFAE5C05E468CA4' -o "$tmp"/"$partFile".json

}
rptParticipants()
{
     echo "User,Join Time,Location,Network Type,Microphone,Camera,Speaker, Version, IP" > "$tmp"/"$partFile".csv
     for part in "$tmp"/*participants.json;
     do
	 jq --arg FILE  $part -r -f "$thisDir"/get.participant.detail.jq "$part" >> "$tmp"/"$partFile".csv
     done
     msg "Participants' file is $tmp/"$partFile".xlsx"
     ssconvert "$tmp"/"$partFile".csv "$tmp"/"$partFile".xlsx
}
downloadRecordings()
{
    ### TODO Put the recordings in a shared space (Dropbox/WISE/
    recDir=~/Recordings
    mkdir -p "$recDir"
    while IFS='' read -r thisItem; do
	jq -r --arg ID "$thisItem"  -f "$thisDir"/get.download.links.jq "$tmp"/big.json >> "$downloadLinks"
    done < "$gThisList"
    while IFS='' read -r thisItem; do
	thisFile=$(echo $thisItem | awk  '{printf "%s-%s.MP4\n", $1, $2}')
	downloadUrl=$(echo $thisItem | awk  '{print $3}')
	if [ ! -f $recDir/$thisFile ]; then
	    wget  --content-disposition -v "$downloadUrl" -O  $recDir/$thisFile
	fi
    done < "$downloadLinks"
}
doParticipation()
{
    msg "Doing Participation"
    :>$tmp/thisParticipation.tsv
    meetingBasics Course

    for file in "$tmp"/*.details.json;
    do
	thisID=$(echo $file | sed -r -e 's/.*([0-9]{11}).*$/\1/g')
	thisTopic=$(jq '.topic' "$file")
	curl -s --location --request GET \
	     'https://api.zoom.us/v2/metrics/meetings/'"$thisID"'/participants?type=past' \
	     --header 'Authorization: Bearer '"$thisAuth"  \
	     -o "$tmp"/"$thisID".participants.json
	thisCount=$(jq -r '.participants[].user_id' "$tmp"/$thisID.participants.json | wc -l)
	printf "%s\t%s\n", "$thisTopic", "$thisCount" >> $tmp/thisParticipation.tsv
    done 
    msg "Participation file is in $tmp/thisParticipation.tsv"
}


while getopts "Kn:dr:Pt:nShvV" opt; do
    shopt -s nocasematch
    #
    # Setting up some variables that we'll use for paths and files
    #
    thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    awkDir=$thisDir/awk
    jqDir=$thisDir/jq
    case ${opt} in
	K )
	    ### -K keep temporary json meeting files (for debugging)
	    keepDetails=true
	    ;;
	d )
	    ### -d Download recordings
	    ### TODO: make this only valid with -r
	    download=true
	    ;;
	n )
	    ### -n "Add note to the start of the report page. Must be quoted string"
	    thisNote="$OPTARG"
	    ;;
	r )
	    getAll=true
	    tmpType=${OPTARG,,} # Use parameter substituion to convert $tmpType to lowercase for easier matching
	    rptType=Recording
	    case "$tmpType" in
		### -r Zoom recording type
		course*)
		    ###        Courses
		    trackingField="Course"
		    rptTitle="$trackingField Recordings"
		    cmd=Recordings
		    rptFile=CourseRecordings.html
		;;
		event*)
		    ###        Events
		    trackingField="Event"
		    rptTitle="$trackingField Recordings"
		    cmd=Recordings
		    rptFile=EventRecordings.html
		    ;;
		committee*)
		    ###        Committee
		    trackingField="Committee Meeting"
		    rptTitle="$trackingField Recordings"
		    cmd=Recordings
		    rptFile=CommitteeRecordings.html
		    ;;
		training*)
		    ###        Training
		    trackingField="Training"
		    rptTitle="$trackingField Recordings"
		    cmd=Recordings
		    rptFile=TrainingRecordings.html				    
		    ;;
		sig**)
		    ###        SIGs
		    trackingField="SIG"
		    rptTitle="$trackingField Recordings"
		    cmd=Recordings
		    rptFile=SIGRecordings.html				    
		    ;;
		* )
		    echo "%% Invalid tracking field for recordngs : $OPTARG"
		    help
		    ;;
	    esac

	    ;;
	S ) # capital S
	    ### -S Simplified output to allow us to use the data in a spreadsheet.
	    simple=true
	    ;;
	P )
	    ### -P  Get course participation stats
	    getAll=true
	    trackingField="Course"
	    rptTitle="Participation for Courses"
	    cmd=Participation
	    ;;
	t )
	    ### -t Zoom meeting type
	    tmpType=$OPTARG
	    tmpType=${tmpType,,}
	    # matching upper or lower, singular or plural
	    msg "Got type $tmpType"
	    case "$tmpType" in
		course*)
		    ###        Courses
		    trackingField="Course"
		    rptTitle="Zoom Links for Courses"
		    awkFile=$awkDir/zoom.courses.awk
		    cmd=Courses
		    rptFile=Courses.html
		;;
		training)
		    ###        Committees
		    trackingField="Training"
		    rptTitle="Zoom Links for Training Sessions"
		    cmd=Mtg
		    rptFile=Training.html
		    awkFile=$awkDir/zoom.events.awk
		    rptType=Training
		    ;;
		committee*)
		    ###        Committees
		    trackingField="Committee Meeting"
		    rptTitle="Zoom Links for Committee Meetings"
		    cmd=Mtg
		    rptFile=Committee.html
		    awkFile=$awkDir/zoom.clubs.awk
		    rptType=Committees
		    ;;
		event*)
		    ###        Events
		    trackingField="Event"
		    rptTitle="Zoom Links for Events"
		    awkFile=$awkDir/zoom.events.awk
		    cmd=Mtg
		    rptFile=Events.html
		    ;;
		club*)
		    ###        Clubs
		    trackingField="Club Meeting"
		    rptTitle="Zoom Links for Clubs and Groups"
		    cmd=Mtg
		    awkFile=$awkDir/zoom.clubs.awk
		    rptType=Clubs
		    rptFile=Clubs.html
		    ;;
		sig*)
		    ###        SIG
		    trackingField="SIG"
		    rptTitle="Zoom Links for Special Interest Groups (SIGS)"
		    cmd=Mtg
		    awkFile=$awkDir/zoom.clubs.awk
		    rptType=SIG
		    rptFile=SIGs.html
		    ;;
		group*)
		    ###        Group
		    trackingField="Group Meeting"
		    rptTitle="Zoom Links for Group Meetings"
		    awkFile=$awkDir/zoom.clubs.awk
		    cmd=Mtg
		    rptType=group
		    rptFile=Groups.html
		    ;;		
		* )
		    echo "%% Invalid meeting type : $OPTARG"
		    help
		    ;;
	    esac
	    ;;
	n )
	    ### -n Don't initialize, i.e., don't delete contents of ~/tmp/zoom
	    init=false
	    ;;
	h )
	    ### -h Print help and exit
	    help
	    ;;
	v )
	    ### -v Set verbose mode
	    verbose="true"
	    ;;
	* )
	    echo "Invalid Option: -$OPTARG" 1>&2
	    exit 1
	    ;;
    esac
done
#
init "$cmd"
setup "$cmd"
if [[ -z $cmd ]]; then
    echo "%% *Error* - Missing meeting type or recording"
    help
fi
do$cmd "$rptType"
#
end_time=$(date -u +%s)
elapsed=$((end_time-start_time))
msg "Elapsed time: $elapsed seconds"
