#!/bin/bash
thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
str="$*"
mtgID=${str//[[:blank:]]/}
echo $mtgID
thisAuth=$(python $thisDir/get.auth.py)
curl --request GET \
     https://api.zoom.us/v2/meetings/'"$mtgID"'/polls \
     -H 'Authorization: Bearer' "$thisAuth"
# content-type: application/json'  
#curl --request POST -url https://api.zoom.us/v2/meetings/$mtgID/polls --header 'Authorization: Bearer '"$thisAuth" \
#      --header 'content-type: application/json'\
#      --data @poll.json


      
